version: '3.8'

services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
