version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Techniza**
      POSTGRES_DB: Techniza
      TZ: America/Mexico_City
      PGTZ: America/Mexico_City
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
